# Generated by Django 3.1.7 on 2021-04-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='med_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_symptoms', models.TextField()),
                ('data_severity', models.TextField()),
                ('medicine_data', models.TextField()),
                ('instructions_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('email', models.CharField(max_length=140)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=5)),
                ('symptoms', models.TextField()),
                ('days', models.CharField(max_length=10)),
                ('severity', models.TextField()),
                ('msz', models.TextField()),
            ],
        ),
    ]
